### ISSUE TITLE
Difference between w/ and w/o Graphics

### ISSUE THREAD

**Issue by liusida** [ja3067/Titan#19]
I ran two same simple experiments with only one particle both w/ and w/o Graphics, and the results are slightly different from each other.

The only difference in source code is I delete the line
```
target_compile_definitions(Titan PUBLIC GRAPHICS)
```
in CMakeLists.txt

I fixed the initial position, and I use `sim.pause(sim.time()+_constant_)` to make sure the times are the same.
w/ Graphics, the final position is 0: (8.11824, -0.497202, -1.86328e-05)
w/o Graphics, the final position is 0: (8.11705, -0.497376, -1.53156e-05)

Will this be an issue?
P.S. I learned a lot from the source code. Thanks.

**Comment by liusida** [comment]
Oh, I figured out. It is because `NUM_QUEUED_KERNELS` is 4 when running w/o Graphics, so the simulation outshoots a little bit more time than the one w/ Graphics.

I think it won't be an issue. The differences won't build up.

```
w/ Graphic

Sim Time: 12.3001

HOST MASSES: 
0: (-1.54791, 0.964772, -9.56595e-05)
1: (0.964772, 0.118667, -9.56595e-05)

w/o Graphic with NUM_QUEUED_KERNELS=4

Sim Time: 12.3004

HOST MASSES: 
0: (-1.54493, 0.964851, -9.31914e-05)
1: (0.964851, 0.118677, -9.31914e-05)

Sim Time: 12.3001 with NUM_QUEUED_KERNELS=1

HOST MASSES: 
0: (-1.54791, 0.964772, -9.56595e-05)
1: (0.964772, 0.118667, -9.56595e-05)
```

**Comment by jacobaustin123** [comment]
Awesome. Glad you figured it out. We have the `NUM_QUEUED_KERNELS` flag because it improves performance slightly to dispatch multiple kernels at one time, but you can only do it in the NOGRAPHICS version because you need to sync the graphics otherwise. Let me know if this becomes a usability issue – you can see that the times are slightly different in both cases. We didn't think this would be a big issue, but if it is, we can change it to be feature equivalent.
