### ISSUE TITLE
Questions regarding parameters

### ISSUE THREAD

**Issue by TK-21st** [ja3067/Titan#8]
1. For each `mass` there is this `setDrag` method which sets a `drag_coefficient` constant. Is this the same as scaling the acceleration of each mass by a constant? Is this same as damping that would look something like (pseudo-code) `mass->acceleration *= drag`
2. How do you set friction of the ground plane that's created using the `sim.createPlane` method? I see that the `creatPlane` method creates `ContactPlane` which doesn't seem to have fricition parameter while `ConstraintPlane` does. 
     * if `ContactPlane` doesn't accept friction parameter, can we replace it with `ConstraintPlane`?
3. If I want to set the response of the ground plane which is currently [hardcoded](https://github.com/ja3067/Titan/blob/12dfe4a8bfdd7ae3d039ffcffe0fb5827a6e912e/src/object.cu#L9) can I do it in some hacky way?

**Comment by TK-21st** [comment]
I think I've answered a few of my own questions:

1. It seems like the drag is literally a drag force applied to the masses. see [here](https://github.com/ja3067/Titan/blob/12dfe4a8bfdd7ae3d039ffcffe0fb5827a6e912e/src/sim.cu#L1086) 
2. No mechanism for damping is in place see [acceleration for masses](https://github.com/ja3067/Titan/blob/12dfe4a8bfdd7ae3d039ffcffe0fb5827a6e912e/src/sim.cu#L1090)
3. `ContactPlane` does not have friction in its [`applyForce` method](https://github.com/ja3067/Titan/blob/12dfe4a8bfdd7ae3d039ffcffe0fb5827a6e912e/src/object.cu#L51)

### Remaining question
1. Would you like to me submit a pull request once I add these features or would you want to do it yourself?
2. `ConstraintPlane` cannot seem to be used as `ContactPlane` **(is this true?)**

**Comment by jacobaustin123** [comment]
Thanks for this! To your first message:

1. That's correct. I'll update the documentation to make that behavior clear.
2. There's currently no mechanism for contact plane friction. The reason for that is that that is very hard to implement in contact based simulations where in practice the mass just bounces off and cannot slide along the surface. If you can think of a good way to do this, feel free to add it or let us know, and we can try to implement it.
3. It's currently hard-coded. Changing it is a little tricky because it's needed as a global __device__ constant on the GPU, which is hard to set/modify at runtime. You could make it a cudaMalloc-ed variable and set it explicitly, or (at a minimum) you might be able to resolve it with a macro or constexpr which you set when instantiating the Simulation class. We're both a bit busy at the end of the semester, so if you'd like to add the feature and submit a pull request, that would be great. Otherwise we can try to add it in the next week or so.

To your second message:
2. That's correct. There actually isn't such a thing as a ConstraintPlane, except as is used internally by CUDA. This aspect of the API leaves something to be desired. If there's a use case you think is difficult as is, we're still very open to remodelling aspects of the API.
